export const GET_DATA_TYPE = "GET_DATA";
export const FILTER_DATA_TYPE = "FILTER_DATA_TYPE";
export const GET_COMMENTS_TYPE = "COMMENTS_DATA_TYPE";
export const IS_LOADING_TYPE = "IS_LOADING_TYPE";
export const IS_UPDATE_TYPE = "IS_UPDATE_TYPE";